import Head from 'next/head'
import Image from 'next/image'
import { BrowserView, MobileView, isBrowser, isMobile, isIOS, isSafari } from 'react-device-detect';
export default function Home() {

  const renderContent = () => {
    if (isBrowser) {
      return <div> Browser</div>
    }
    if (isMobile) {
      return <div> mobile</div>
    }
    if (isIOS) {
      return <div> IOS</div>
    }
    if (isSafari) {
      return <div> Safari</div>
    }
  }

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      page index.js

      {renderContent()}


      <p>sss</p>
    </div>
  )
}
