import Head from 'next/head'
import Image from 'next/image'
import useIsIOS from '../components/useIsIOS'


export default function Home() {


  const { prompt } = useIsIOS();

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      page index.js
      <p>{prompt}</p>




      <p>sss</p>
    </div>
  )
}
